<?php

$IsLocal = true;
 $conf['securepages_enable'] = 0;
$subdomain =  explode(".",$_SERVER['HTTP_HOST']);
$subdomain = array_shift($subdomain);

echo $subdomain;

// Include our basic dev settings.
if (file_exists('sites/default/global.inc')) {
  require('sites/default/global.inc');
}



	$conf['file_public_path'] = 'sites/' . $subdomain . '.stonybrook.edu/files';
	$conf['file_temporary_path'] = 'sites/' . $subdomain . '.stonybrook.edu/tmp-files';


///////////////////////////////////////////////////////////////////////
//       Please don't edit anything between <@@ADCP_CONF@@> tags     //
// This section is autogenerated by Acquia Dev Desktop Control Panel //
///////////////////////////////////////////////////////////////////////
//<@@ADCP_CONF@@>


//D7 DB config
$databases = array('default' => array('default' => array(
    'driver' => 'mysql',
    'database' => 'drupal',
    'username' => 'drupaluser',
    'password' => '',
    'host' => '127.0.0.1',
    'port' => 33066 )));

//password=drupal
//</@@ADCP_CONF@@>
