<?php
/**
 * @file
 * Default file.
 */

/**
 * Implements hook_views_api().
 */
function views_book_chapter_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_help().
 */
function views_book_chapter_help($path, $arg) {
  $output = '';

  switch ($path) {

    case 'admin/help#views-book-chapter':
      $output .= '<p>' . t('Views book chapter: TODO documentation.') . '</p>';
  }

  return $output;
}

/**
 * Get the book tree with chapter numbers.
 *
 * I take the idea with this module, but ussing the menu system.
 * (bookchapters)[http://dgo.to/bookchapters]
 *
 * See:
 * - @link _bookchapters_get_chapter_numbering @endlink
 *
 * @param int $bid
 *   Book id.
 *
 * @return array
 *   Array with the chapters numbers.
 */
function views_book_chapter_get_book_tree($bid = 0, $show_childs = FALSE) {
  static $book_ckapters;

  // Sanitized, just in case.
  $bid = (int) check_plain($bid);

  if (empty($bid)) {
    drupal_set_message(t('Views book chapters is missing something.'), 'error', FALSE);
    watchdog('views_book_chapter', 'ERROR: We are getting a weird bid: @bid', array('@bid' => print_r($bid, TRUE)), WATCHDOG_ERROR);
  }

  if (!empty($book_ckapters[$bid])) {
    return $book_ckapters;
  }

  // We're caching book into a library.
  $book_chapters = cache_get('views_book_chapter_book_library');

  if (!empty($book_ckapters[$bid])) {
    return $book_ckapters[$bid];
  }

  $node = node_load($bid);

  $tree = book_menu_subtree_data($node->book);
  // Do not include it self.
  $tree = array_shift($tree);

  if ($tree['below']) {
    $index = _views_book_chapter_get_book_index($tree['below'], $show_childs);
  }

  $book_ckapters[$bid] = $index;

  cache_set('views_book_chapter_book_library', $book_ckapters);

  return $book_ckapters[$bid];

}

/**
 * Internal function to handle the books chapters nesting.
 *
 * @see views_book_chapter_handler_filter_book_chapters::value_form()
 *
 * @param int $menu_tree
 *   Book id.
 * @param bool $show_childs
 *   Bool, settings to show or hide the childs chapters.
 * @param string $supreme_child
 *   Bad hack to handle the nesting in the select.
 *
 * @return array
 *   With the index book.
 */
function _views_book_chapter_get_book_index($menu_tree, $show_childs = TRUE, $supreme_child = '') {
  static $index;

  // This is the most advantge code you never seen.
  $nesting_index = $supreme_child . '- ';

  foreach ($menu_tree as $leef) {
    $index[$leef['link']['mlid']] = $nesting_index . $leef['link']['title'];

    if (!empty($leef['below']) && $show_childs) {
      $index = _views_book_chapter_get_book_index($leef['below'], TRUE, $supreme_child . '-');
    }
  }

  return $index;
}
